# Generated by Django 6.0.4 on 2026-04-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': '预约', 'verbose_name_plural': '预约'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': '医生', 'verbose_name_plural': '医生'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': '患者', 'verbose_name_plural': '患者'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(db_index=True, verbose_name='预约时间'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'appointment_time'], name='clinic_appo_patient_096fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_time'], name='clinic_appo_doctor__ff6e27_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status'], name='clinic_appo_doctor__9fdbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='clinic_appo_patient_845bfe_idx'),
        ),
    ]
