# Generated by Django 6.0.4 on 2026-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='头像URL'),
        ),
        migrations.AddField(
            model_name='patient',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='头像URL'),
        ),
    ]
